export type JohtoTrainerRole =
  | "regular-trainer"
  | "gym-leader"
  | "elite-four"
  | "champion";

export type JohtoTrainer = {
  id: string;
  name: string;
  role: JohtoTrainerRole;
  location: string;
  sprite: string;
  pokemonTeam: string[];
};

export type JohtoStage = {
  id: string;
  number: number;
  name: string;
  city: string;
  badge: string;
  regularTrainerIds: string[];
  gymLeaderId: string;
};

const SHOWDOWN_TRAINER_BASE = "/images/trainers/showdown/raw";

export const JOHTO_REGULAR_TRAINERS: JohtoTrainer[] = [
  {
    id: "johto-youngster",
    name: "Youngster",
    role: "regular-trainer",
    location: "Johto Route",
    sprite: `${SHOWDOWN_TRAINER_BASE}/youngster-gen2.png`,
    pokemonTeam: ["Sentret", "Rattata"],
  },
  {
    id: "johto-bug-catcher",
    name: "Bug Catcher",
    role: "regular-trainer",
    location: "Johto Route",
    sprite: `${SHOWDOWN_TRAINER_BASE}/bugcatcher-gen2.png`,
    pokemonTeam: ["Caterpie", "Spinarak"],
  },
  {
    id: "johto-bird-keeper",
    name: "Bird Keeper",
    role: "regular-trainer",
    location: "Johto Route",
    sprite: `${SHOWDOWN_TRAINER_BASE}/birdkeeper-gen2.png`,
    pokemonTeam: ["Pidgey", "Hoothoot"],
  },
  {
    id: "johto-lass",
    name: "Lass",
    role: "regular-trainer",
    location: "Johto Route",
    sprite: `${SHOWDOWN_TRAINER_BASE}/lass-gen2.png`,
    pokemonTeam: ["Marill", "Jigglypuff"],
  },
  {
    id: "johto-schoolboy",
    name: "Schoolboy",
    role: "regular-trainer",
    location: "Johto Route",
    sprite: `${SHOWDOWN_TRAINER_BASE}/schoolboy-gen2.png`,
    pokemonTeam: ["Tangela", "Wooper"],
  },
  {
    id: "johto-camper",
    name: "Camper",
    role: "regular-trainer",
    location: "Azalea Outskirts",
    sprite: `${SHOWDOWN_TRAINER_BASE}/camper-gen2.png`,
    pokemonTeam: ["Sandshrew", "Phanpy"],
  },
  {
    id: "johto-picnicker",
    name: "Picnicker",
    role: "regular-trainer",
    location: "Azalea Outskirts",
    sprite: `${SHOWDOWN_TRAINER_BASE}/picnicker-gen2.png`,
    pokemonTeam: ["Nidoran F", "Skiploom"],
  },
  {
    id: "johto-sage",
    name: "Sage",
    role: "regular-trainer",
    location: "Sprout Tower",
    sprite: `${SHOWDOWN_TRAINER_BASE}/sage-gen2.png`,
    pokemonTeam: ["Bellsprout", "Hoothoot"],
  },
  {
    id: "johto-hiker",
    name: "Hiker",
    role: "regular-trainer",
    location: "Union Cave",
    sprite: `${SHOWDOWN_TRAINER_BASE}/hiker-gen2.png`,
    pokemonTeam: ["Geodude", "Onix"],
  },
  {
    id: "johto-firebreather",
    name: "Firebreather",
    role: "regular-trainer",
    location: "Union Cave",
    sprite: `${SHOWDOWN_TRAINER_BASE}/firebreather-gen2.png`,
    pokemonTeam: ["Koffing", "Magmar"],
  },
  {
    id: "johto-beauty",
    name: "Beauty",
    role: "regular-trainer",
    location: "Goldenrod City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/beauty-gen2.png`,
    pokemonTeam: ["Clefairy", "Snubbull"],
  },
  {
    id: "johto-gentleman",
    name: "Gentleman",
    role: "regular-trainer",
    location: "Goldenrod City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/gentleman-gen2.png`,
    pokemonTeam: ["Growlithe", "Persian"],
  },
  {
    id: "johto-pokefan",
    name: "Pokefan",
    role: "regular-trainer",
    location: "Goldenrod City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/pokefan-gen2.png`,
    pokemonTeam: ["Pikachu", "Raichu"],
  },
  {
    id: "johto-pokefan-f",
    name: "Pokefan",
    role: "regular-trainer",
    location: "Goldenrod City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/pokefanf-gen2.png`,
    pokemonTeam: ["Cleffa", "Igglybuff"],
  },
  {
    id: "johto-twins",
    name: "Twins",
    role: "regular-trainer",
    location: "Goldenrod City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/twins-gen2.png`,
    pokemonTeam: ["Ledyba", "Spinarak"],
  },
  {
    id: "johto-medium",
    name: "Medium",
    role: "regular-trainer",
    location: "Ecruteak City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/sage-gen2.png`,
    pokemonTeam: ["Gastly", "Haunter"],
  },
  {
    id: "johto-kimono-girl",
    name: "Kimono Girl",
    role: "regular-trainer",
    location: "Ecruteak City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/kimonogirl-gen2.png`,
    pokemonTeam: ["Eevee", "Espeon"],
  },
  {
    id: "johto-psychic",
    name: "Psychic",
    role: "regular-trainer",
    location: "Ecruteak City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/psychic-gen2.png`,
    pokemonTeam: ["Abra", "Kadabra"],
  },
  {
    id: "johto-juggler",
    name: "Juggler",
    role: "regular-trainer",
    location: "Ecruteak City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/juggler-gen2.png`,
    pokemonTeam: ["Voltorb", "Mr. Mime"],
  },
  {
    id: "johto-super-nerd",
    name: "Super Nerd",
    role: "regular-trainer",
    location: "Ecruteak City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/supernerd-gen2.png`,
    pokemonTeam: ["Magnemite", "Grimer"],
  },
  {
    id: "johto-sailor",
    name: "Sailor",
    role: "regular-trainer",
    location: "Olivine Harbor",
    sprite: `${SHOWDOWN_TRAINER_BASE}/sailor-gen2.png`,
    pokemonTeam: ["Poliwag", "Machop"],
  },
  {
    id: "johto-swimmer-m",
    name: "Swimmer",
    role: "regular-trainer",
    location: "Olivine Harbor",
    sprite: `${SHOWDOWN_TRAINER_BASE}/swimmerm-gen2.png`,
    pokemonTeam: ["Tentacool", "Quagsire"],
  },
  {
    id: "johto-swimmer-f",
    name: "Swimmer",
    role: "regular-trainer",
    location: "Olivine Harbor",
    sprite: `${SHOWDOWN_TRAINER_BASE}/swimmerf-gen2.png`,
    pokemonTeam: ["Horsea", "Corsola"],
  },
  {
    id: "johto-blackbelt",
    name: "Black Belt",
    role: "regular-trainer",
    location: "Cianwood City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/blackbelt-gen2.png`,
    pokemonTeam: ["Machop", "Hitmontop"],
  },
  {
    id: "johto-guitarist",
    name: "Guitarist",
    role: "regular-trainer",
    location: "Olivine Harbor",
    sprite: `${SHOWDOWN_TRAINER_BASE}/guitarist-gen2.png`,
    pokemonTeam: ["Voltorb", "Electabuzz"],
  },
  {
    id: "johto-boarder",
    name: "Boarder",
    role: "regular-trainer",
    location: "Mahogany Town",
    sprite: `${SHOWDOWN_TRAINER_BASE}/boarder-gen2.png`,
    pokemonTeam: ["Swinub", "Delibird"],
  },
  {
    id: "johto-skier",
    name: "Skier",
    role: "regular-trainer",
    location: "Mahogany Town",
    sprite: `${SHOWDOWN_TRAINER_BASE}/skier-gen2.png`,
    pokemonTeam: ["Jynx", "Sneasel"],
  },
  {
    id: "johto-scientist",
    name: "Scientist",
    role: "regular-trainer",
    location: "Lake of Rage",
    sprite: `${SHOWDOWN_TRAINER_BASE}/scientist-gen2.png`,
    pokemonTeam: ["Magnemite", "Porygon2"],
  },
  {
    id: "johto-rocket-grunt",
    name: "Rocket Grunt",
    role: "regular-trainer",
    location: "Rocket Hideout",
    sprite: `${SHOWDOWN_TRAINER_BASE}/rocketgrunt-gen2.png`,
    pokemonTeam: ["Zubat", "Raticate"],
  },
  {
    id: "johto-rocket-grunt-f",
    name: "Rocket Grunt",
    role: "regular-trainer",
    location: "Rocket Hideout",
    sprite: `${SHOWDOWN_TRAINER_BASE}/rocketgruntf-gen2.png`,
    pokemonTeam: ["Ekans", "Vileplume"],
  },
  {
    id: "johto-ace-trainer",
    name: "Ace Trainer",
    role: "regular-trainer",
    location: "Blackthorn City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/acetrainer-gen2.png`,
    pokemonTeam: ["Dragonair", "Piloswine"],
  },
  {
    id: "johto-ace-trainer-f",
    name: "Ace Trainer",
    role: "regular-trainer",
    location: "Blackthorn City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/acetrainerf-gen2.png`,
    pokemonTeam: ["Seadra", "Skarmory"],
  },
  {
    id: "johto-teacher",
    name: "Teacher",
    role: "regular-trainer",
    location: "Blackthorn City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/teacher-gen2.png`,
    pokemonTeam: ["Aipom", "Girafarig"],
  },
  {
    id: "johto-officer",
    name: "Officer",
    role: "regular-trainer",
    location: "Blackthorn City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/officer-gen2.png`,
    pokemonTeam: ["Growlithe", "Noctowl"],
  },
  {
    id: "johto-pokemaniac",
    name: "Pokemaniac",
    role: "regular-trainer",
    location: "Blackthorn City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/pokemaniac-gen2.png`,
    pokemonTeam: ["Rhyhorn", "Kangaskhan"],
  },
  {
    id: "johto-burglar",
    name: "Burglar",
    role: "regular-trainer",
    location: "Victory Road",
    sprite: `${SHOWDOWN_TRAINER_BASE}/burglar-gen2.png`,
    pokemonTeam: ["Koffing", "Magcargo"],
  },
  {
    id: "johto-biker",
    name: "Biker",
    role: "regular-trainer",
    location: "Victory Road",
    sprite: `${SHOWDOWN_TRAINER_BASE}/biker-gen2.png`,
    pokemonTeam: ["Grimer", "Weezing"],
  },
  {
    id: "johto-rocket-executive",
    name: "Rocket Executive",
    role: "regular-trainer",
    location: "Victory Road",
    sprite: `${SHOWDOWN_TRAINER_BASE}/rocketexecutive-gen2.png`,
    pokemonTeam: ["Houndour", "Koffing"],
  },
  {
    id: "johto-rocket-executive-f",
    name: "Rocket Executive",
    role: "regular-trainer",
    location: "Victory Road",
    sprite: `${SHOWDOWN_TRAINER_BASE}/rocketexecutivef-gen2.png`,
    pokemonTeam: ["Murkrow", "Vileplume"],
  },
  {
    id: "johto-rival",
    name: "Rival",
    role: "regular-trainer",
    location: "Victory Road",
    sprite: `${SHOWDOWN_TRAINER_BASE}/silver-gen2.png`,
    pokemonTeam: ["Sneasel", "Magneton", "Golbat"],
  },
];

export const JOHTO_GYM_LEADERS: JohtoTrainer[] = [
  {
    id: "johto-falkner",
    name: "Falkner",
    role: "gym-leader",
    location: "Violet City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/falkner.png`,
    pokemonTeam: ["Pidgey", "Pidgeotto"],
  },
  {
    id: "johto-bugsy",
    name: "Bugsy",
    role: "gym-leader",
    location: "Azalea Town",
    sprite: `${SHOWDOWN_TRAINER_BASE}/bugsy.png`,
    pokemonTeam: ["Metapod", "Kakuna", "Scyther"],
  },
  {
    id: "johto-whitney",
    name: "Whitney",
    role: "gym-leader",
    location: "Goldenrod City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/whitney.png`,
    pokemonTeam: ["Clefairy", "Miltank"],
  },
  {
    id: "johto-morty",
    name: "Morty",
    role: "gym-leader",
    location: "Ecruteak City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/morty.png`,
    pokemonTeam: ["Gastly", "Haunter", "Gengar", "Haunter"],
  },
  {
    id: "johto-chuck",
    name: "Chuck",
    role: "gym-leader",
    location: "Cianwood City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/chuck.png`,
    pokemonTeam: ["Primeape", "Poliwrath"],
  },
  {
    id: "johto-jasmine",
    name: "Jasmine",
    role: "gym-leader",
    location: "Olivine City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/jasmine.png`,
    pokemonTeam: ["Magnemite", "Magnemite", "Steelix"],
  },
  {
    id: "johto-pryce",
    name: "Pryce",
    role: "gym-leader",
    location: "Mahogany Town",
    sprite: `${SHOWDOWN_TRAINER_BASE}/pryce.png`,
    pokemonTeam: ["Seel", "Dewgong", "Piloswine"],
  },
  {
    id: "johto-clair",
    name: "Clair",
    role: "gym-leader",
    location: "Blackthorn City",
    sprite: `${SHOWDOWN_TRAINER_BASE}/clair.png`,
    pokemonTeam: ["Dragonair", "Dragonair", "Dragonair", "Kingdra"],
  },
];

export const JOHTO_ELITE_FOUR: JohtoTrainer[] = [
  {
    id: "johto-will",
    name: "Will",
    role: "elite-four",
    location: "Indigo Plateau",
    sprite: `${SHOWDOWN_TRAINER_BASE}/will.png`,
    pokemonTeam: ["Xatu", "Jynx", "Exeggutor", "Slowbro", "Xatu"],
  },
  {
    id: "johto-koga",
    name: "Koga",
    role: "elite-four",
    location: "Indigo Plateau",
    sprite: `${SHOWDOWN_TRAINER_BASE}/koga-gen2.png`,
    pokemonTeam: ["Ariados", "Venomoth", "Forretress", "Muk", "Crobat"],
  },
  {
    id: "johto-bruno",
    name: "Bruno",
    role: "elite-four",
    location: "Indigo Plateau",
    sprite: `${SHOWDOWN_TRAINER_BASE}/bruno-gen2.png`,
    pokemonTeam: ["Hitmontop", "Hitmonlee", "Hitmonchan", "Onix", "Machamp"],
  },
  {
    id: "johto-karen",
    name: "Karen",
    role: "elite-four",
    location: "Indigo Plateau",
    sprite: `${SHOWDOWN_TRAINER_BASE}/karen.png`,
    pokemonTeam: ["Umbreon", "Vileplume", "Murkrow", "Gengar", "Houndoom"],
  },
];

export const JOHTO_CHAMPION: JohtoTrainer = {
  id: "johto-lance",
  name: "Lance",
  role: "champion",
  location: "Indigo Plateau",
  sprite: `${SHOWDOWN_TRAINER_BASE}/lance-gen2.png`,
  pokemonTeam: ["Gyarados", "Dragonite", "Dragonite", "Aerodactyl", "Charizard", "Dragonite"],
};

export const JOHTO_STAGES: JohtoStage[] = [
  {
    id: "johto-stage-1",
    number: 1,
    name: "Violet City Gym",
    city: "Violet City",
    badge: "Zephyr Badge",
    regularTrainerIds: [
      "johto-youngster",
      "johto-bug-catcher",
      "johto-bird-keeper",
      "johto-lass",
      "johto-schoolboy",
    ],
    gymLeaderId: "johto-falkner",
  },
  {
    id: "johto-stage-2",
    number: 2,
    name: "Azalea Gym",
    city: "Azalea Town",
    badge: "Hive Badge",
    regularTrainerIds: [
      "johto-camper",
      "johto-picnicker",
      "johto-sage",
      "johto-hiker",
      "johto-firebreather",
    ],
    gymLeaderId: "johto-bugsy",
  },
  {
    id: "johto-stage-3",
    number: 3,
    name: "Goldenrod Gym",
    city: "Goldenrod City",
    badge: "Plain Badge",
    regularTrainerIds: [
      "johto-beauty",
      "johto-gentleman",
      "johto-pokefan",
      "johto-pokefan-f",
      "johto-twins",
    ],
    gymLeaderId: "johto-whitney",
  },
  {
    id: "johto-stage-4",
    number: 4,
    name: "Ecruteak Gym",
    city: "Ecruteak City",
    badge: "Fog Badge",
    regularTrainerIds: [
      "johto-medium",
      "johto-kimono-girl",
      "johto-psychic",
      "johto-juggler",
      "johto-super-nerd",
    ],
    gymLeaderId: "johto-morty",
  },
  {
    id: "johto-stage-5",
    number: 5,
    name: "Cianwood Gym",
    city: "Cianwood City",
    badge: "Storm Badge",
    regularTrainerIds: [
      "johto-sailor",
      "johto-swimmer-m",
      "johto-swimmer-f",
      "johto-blackbelt",
      "johto-guitarist",
    ],
    gymLeaderId: "johto-chuck",
  },
  {
    id: "johto-stage-6",
    number: 6,
    name: "Olivine Gym",
    city: "Olivine City",
    badge: "Mineral Badge",
    regularTrainerIds: [
      "johto-boarder",
      "johto-skier",
      "johto-scientist",
      "johto-rocket-grunt",
      "johto-rocket-grunt-f",
    ],
    gymLeaderId: "johto-jasmine",
  },
  {
    id: "johto-stage-7",
    number: 7,
    name: "Mahogany Gym",
    city: "Mahogany Town",
    badge: "Glacier Badge",
    regularTrainerIds: [
      "johto-ace-trainer",
      "johto-ace-trainer-f",
      "johto-teacher",
      "johto-officer",
      "johto-pokemaniac",
    ],
    gymLeaderId: "johto-pryce",
  },
  {
    id: "johto-stage-8",
    number: 8,
    name: "Blackthorn Gym",
    city: "Blackthorn City",
    badge: "Rising Badge",
    regularTrainerIds: [
      "johto-burglar",
      "johto-biker",
      "johto-rocket-executive",
      "johto-rocket-executive-f",
      "johto-rival",
    ],
    gymLeaderId: "johto-clair",
  },
];

export const JOHTO_REGION = {
  id: "johto",
  name: "Johto",
  pokemonIdRange: [152, 251] as const,
  stages: JOHTO_STAGES,
  regularTrainers: JOHTO_REGULAR_TRAINERS,
  gymLeaders: JOHTO_GYM_LEADERS,
  eliteFour: JOHTO_ELITE_FOUR,
  champion: JOHTO_CHAMPION,
};

